function squareplot2x2(X1,Y1)
%CREATEFIGURE(X1)
%  X1:  vector of x data

%  Auto-generated by MATLAB on 26-Aug-2017 11:37:42

% Create figure
%figure1 = figure;

% Create axes
axes1 = axes('Parent',gcf);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',2);

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[-2 2]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-2 2]);
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'LineWidth',2,'XAxisLocation','origin',...
    'YAxisLocation','origin','YTick',[-2 -1 0 1 2]);
